// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings`

interface CloudflareBindings {
	CHARACTER_LOGS: KVNamespace;
	CHARACTER_HISTORY: KVNamespace;
	JWT_SECRET: string;
	CHARACTER_OBJECT: DurableObjectNamespace<import("./src/index").CharacterObject>;
	DB: D1Database;
}
