name: Validation

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Install dependencies
      run: bun install

    - name: Generate Prisma Client
      run: bun run prisma:generate

    - name: Type check
      run: bun run typecheck

    - name: Lint
      run: bun run lint

    - name: Build
      run: bun run build

    - name: Test
      run: bun test --coverage --bail
      env:
        CI: true 